### ISSUE TITLE
Freezes and shows no output

### ISSUE THREAD

**Issue by CharDSonDev** [karelkryda/universal-speedtest#10]
Using the 3 examples in the documentation, the program freezes and does not show an output in the terminal.

![image](https://user-images.githubusercontent.com/36754778/145701657-ec181c83-cbaf-448f-9d9c-fc5542da08b5.png)

**Comment by karelkryda** [comment]
Hi,
How long did you wait for the test to complete and view the result? 

You can add the "debug: true" parameter to the constructor to see what exactly is happening. 

Thanks

**Comment by CharDSonDev** [comment]
# Cloudflare

**Finish Time:** 6 minutes

>Ping: 68.049 ms
>Download speed: 1.1375 MBps
>Upload speed: 0.88 Mbps

__Debug__

speed.cloudflare.com data were obtained
Client - IP (DO)
Server: PAP (Port-au-Prince - North America), 252.97 km, 54.472 ms

**Time:** 5 minutes

>Download: 0.885 MBps

**Finish Time:** 7 minutes

>Upload: 0.77 Mbps
>Test performed in 414.7 seconds
>Ping: 63.021 ms
>Download speed: 0.885 MBps
>Upload speed: 0.77 Mbps

# SpeedTest

**Time:** 1 minute

>[urllib:warn] [Sun Dec 12 2021 17:07:21 GMT-0400 (Alaska Standard Time)] [1] [worker:33257] GET http://mrz.speed.com.do:8080/speedtest/random1500x1500.jpg callback twice!!!

**Finish Time:** 8 minutes
The system (EarlyOOM) killed the process due to excessive use of RAM

__Debug__

speedtest.net config was obtained
Client - Claro Dominican Republic (IP)
Server: Claro Dominicana (Santo Domingo - Dominican Republic), 3.23 km, 28.076 ms

**Time:** 2 minutes

>[urllib:warn] [Sun Dec 12 2021 17:24:13 GMT-0400 (Alaska Standard Time)] [1] [worker:34653] GET http://mrz.speed.com.do:8080/speedtest/random2500x2500.jpg callback twice!!!
>Download: 0.28875 MBps

**Finish Time:** 8 minutes
The system (EarlyOOM) killed the process due to excessive use of RAM

**Comment by CharDSonDev** [comment]
It worked for me, thanks

**Comment by karelkryda** [comment]
If everything is OK, I will close this issue now. If you need help with something else, do not hesitate to create a new issue.

P.S: I'll try to create something like a FAQ in the documentation and suggest troubleshooting procedures (I'll include your problem as an example).
I will also try to improve the settings of other tests so that they do not wait for completion as in the speedtest.net test.
