### ISSUE TITLE
[BUG] unnecessary performance impact in upload test

### ISSUE THREAD

**Issue by zkx5xkt** [karelkryda/universal-speedtest#18]
**Describe the bug**
`Object.keys(data)` for `string` data lead to high performance impact (+gc) for long strings
which block event loop for long time

**To Reproduce**
\-

**Expected behavior**
\-

**Screenshots**
single speed test with default options:
![image](https://user-images.githubusercontent.com/58633293/164561548-6fc18ad4-0d5a-4149-a875-7e4e69aca744.png)

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Node.js version: 16
 - Universal Speedtest version: 2.0.4
 - Speed test using: speed.cloudflare.com

**Additional context**
\-

**Comment by zkx5xkt** [comment]
You are amazing!
I don't see any performance issues anymore.

Thank you

**Comment by karelkryda** [comment]
Hi @zkx5xkt,

Based on the problem you have raised here, I think you could potentially help me with my thinking about HTTP request libraries. Could you please visit [this discussion](https://github.com/karelkryda/universal-speedtest/discussions/25)? 

Thank you in advance
