### ISSUE TITLE
[BUG] SyntaxError: Unexpected token at the compilation

### ISSUE THREAD

**Issue by Sebastien-Lampazona** [karelkryda/universal-speedtest#22]
**Describe the bug**
With brunch during compilation i have 2 errors : 

```
error: Processing of node_modules/universal-speedtest/dist/Cloudflare.js failed. SyntaxError: Unexpected token (98:14)
```
```
error: Processing of node_modules/universal-speedtest/dist/Speedtest.js failed. SyntaxError: Unexpected token (123:14)
```

**Desktop (please complete the following information):**
 - OS: WSL2 on windows
 - Node.js version: 16.14.1
 - Universal Speedtest version: 2.0.5

![image](https://user-images.githubusercontent.com/2599774/173073759-184229f7-922b-44b4-81e4-efb26d36efea.png)

**Comment by karelkryda** [comment]
Hi,
could you please send me a screenshot of that line? I don't have a JavaScript version built with me right now.
Thanks in advance

**Comment by karelkryda** [comment]
Hi,
due to inactivity, I am closing this issue. If necessary, do not hesitate to reopen it.
Thank you for your understanding
