### ISSUE TITLE
[FEATURE]  Add ESM support

### ISSUE THREAD

**Issue by arcinston** [karelkryda/universal-speedtest#27]
<img width="1101" alt="image" src="https://github.com/karelkryda/universal-speedtest/assets/69193694/4553084a-048e-467e-a359-0a23d7a91339">

**Comment by karelkryda** [comment]
Hi,
I recently started modifying the library in an effort to release version `3.0.0`, which I never released.
The changes include packaging of both CJS and ESM versions of the library. I'm also removing the use of `urllib` in an effort to allow React Native to run, for example.
I'm also completely redesigning the way I measure with Ookla Speedtest. Thanks to the changes, the measurement should be much more accurate. 

I currently have no idea when the new version could be released. 

Thank you for the feature request and patience
Have a nice day

**Comment by karelkryda** [comment]
Hello @arcinston,
I just [released](https://github.com/karelkryda/universal-speedtest/releases/tag/v3.0.0-rc.0) the release candidate of version `3.0.0`.
You can install and test the library using:
```bash
npm install --save universal-speedtest@next
```

The new documentation can be found here: https://karel-kryda.gitbook.io/universal-speedtest/v/3

I hope everything will work as expected 😉.

**Comment by arcinston** [comment]
that's soo awesome 
will try 

thanks for all the awesome work ❤️

**Comment by karelkryda** [comment]
Fixed in the latest release `3.0.0` 🎄

**Comment by arcinston** [comment]
merry christmas @karelkryda 🎄
