### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by adithyapaib** [karelkryda/universal-speedtest#4]
![Screenshot from 2021-07-14 22-17-51](https://user-images.githubusercontent.com/40488244/125660966-b185adce-a0dd-432d-a8fb-1327059794a5.png)

**Comment by karelkryda** [comment]
Hi,
can I ask you how long did you wait? This test can run 1 minute (depends on your internet speed and selected timeout).
Thanks

**Comment by adithyapaib** [comment]
yes i did wait around 2 mins and also I have 200mbps connections can u just check if it works once?

**Comment by karelkryda** [comment]
![image](https://user-images.githubusercontent.com/59953812/125668467-0842d751-e321-447f-ba2a-2ee6fac2ccee.png)

Works perfectly for me.
Can you ask what version of NodeJS are you using?

Thanks

**Comment by vaibhavgadekar** [comment]
can we use this as api??

**Comment by karelkryda** [comment]
> can we use this as api??

please open own issue and we can talk there :)

**Comment by karelkryda** [comment]
Hello,
I would like to inform you that a beta version of **Universal Speedtest v2** has been released, which contacts measuring servers without using Puppeteer (chromium browser) and should solve most problems.

For this reason, I am now closing this issue, but if you find a problem, do not hesitate to open a new problem.

Thank you for understanding
