### ISSUE TITLE
Module not found: Can't resolve 'http2

### ISSUE THREAD

**Issue by fapjsc** [karelkryda/universal-speedtest#5]
Module not found: Can't resolve 'http2

**Comment by karelkryda** [comment]
Hello,
I would like to inform you that a beta version of **Universal Speedtest v2** has been released, which contacts measuring servers without using Puppeteer (chromium browser) and should solve most problems.

For this reason, I am now closing this issue, but if you find a problem, do not hesitate to open a new problem.

Thank you for understanding
