### ISSUE TITLE
Version without Puppeteer

### ISSUE THREAD

**Issue by chrisspiegl** [karelkryda/universal-speedtest#6]
Hi, I just found this while trying to use speedtest.net for some speed testing in my node.js app.

I like the general idea behind this package, however, I wonder if a version without puppeteer would be better. Puppeteer can be a pretty intense resource hog and thus not really desirable to have running in my projects.

I've seen that other libraries may support this and maybe this lib could be a combination of those efforts and make this the best / most performant one.

**Comment by karelkryda** [comment]
Hello,
I am glad for your interest in using this package. I am aware that everything is not being handled in the best way at the current stage and I will have to look into it in the near future (perhaps on the weekend).

You mention certain libraries as a replacement for Puppeteer. Could you send me some references so I can see what exactly you mean?

P.S .: I am inclined to replace Puppeteer with another library, because Puppeteer is sometimes quite unpredictable and can sometimes cause problems.

Thank you

**Comment by chrisspiegl** [comment]
Great to hear you are interested in continuing the development.

In regards to Puppeteer: I think it's a great tool just not for many things — though easy to get started with.

In regards to Speedtesting, I found some libraries which work without Puppetter but also have issues in themselves.

One lib is https://www.npmjs.com/package/speedtest-net … this one though is currently broken on the most current Node versions. It seems that this one uses the Speedtest.net API directly without puppetter.

And then there is https://github.com/KNawm/speed-cloudflare-cli which uses the Cloudflare Speed test. Sadly right now it does not have a programm api and only offers the CLI version. But it too does not use Puppeteer.

**Comment by karelkryda** [comment]
https://www.npmjs.com/package/speedtest-net - It looks like it uses speedtest-cli
https://github.com/KNawm/speed-cloudflare-cli - looks interesting, I'll definitely look at this package and I'll probably implement Cloudflare Speedtest in my package.

I am currently working on using the speedtest-cli system in my project. It's about 2000 lines of code, which will take some time, but I've probably come up with an alternative to use.

**Comment by chrisspiegl** [comment]
That's quite interesting that the `speedtest-net` package uses the cli and just downloads that in the background (didn't know before, I interpreted it would use an API of some sort since it had all the compression stuff in the `package.json`).

But yea, maybe you can take what they are doing and somehow implement those things in your project to build on top of these things.

For the time being, I have my speedtest working with your Fast.com implementation.

**Comment by karelkryda** [comment]
Hello,
I would like to inform you that I am working intensively on Universal Speedtest v2, which will contact measuring servers without the use of Puppeteer (chromium browser) and should solve most problems.

You can monitor the current progress of v2 development in the **Projects** tab or by using [this link](https://github.com/karelkryda/universal-speedtest/projects/1).

Thank you for your patience

**Comment by chrisspiegl** [comment]
@karelkryda That's awesome news, I am very much looking forward to this and will be ready to test whenever you have some alpha/beta release ready 👍.

**Comment by karelkryda** [comment]
Hello,
I would like to inform you that a beta version of **Universal Speedtest v2** has been released, which contacts measuring servers without using Puppeteer (chromium browser) and should solve most problems.

For this reason, I am now closing this issue, but if you find a problem, do not hesitate to open a new problem.

Thank you for understanding

**Comment by chrisspiegl** [comment]
Tested the new version and it works great. love the update and the implementation of SpeedTest & Cloudflare.

**Comment by karelkryda** [comment]
Thank you for the feedback. I'm glad you like the update.
