### ISSUE TITLE
SpeedTest times out / Fast does not

### ISSUE THREAD

**Issue by chrisspiegl** [karelkryda/universal-speedtest#7]
Hi, I am used to using Speedtest.net for my testing but when I select it with a 60000 timeout it does not complete. But the Fast.com speed test does work with 60000 timeout.

I am measuring Upload and Download.

I am not 100% sure, maybe the Speedtest.net integration is not working properly? Or is Fast.com just faster… *no pun intended*

**Comment by karelkryda** [comment]
Hello,
I would like to inform you that a beta version of **Universal Speedtest v2** has been released, which contacts measuring servers without using Puppeteer (chromium browser) and should solve most problems.

For this reason, I am now closing this issue, but if you find a problem, do not hesitate to open a new problem.

Thank you for understanding

**Comment by chrisspiegl** [comment]
Nice work, I was able to test now and it was great. Love the update.

**Comment by chrisspiegl** [comment]
I have updated my scripts and it works great. Thank you for the update.

Chris Spiegl

ChrisSpiegl.com | Consulting <https://ChrisSpiegl.com/consulting> | What I
am doing /now <https://ChrisSpiegl.com/now>

YouTube Channel <https://ChrisSpiegl.com/youtube> | Macher.Cafe (German
Podcast) <https://ThatMaker.Life>

PGP Public Key <https://ChrisSpiegl.com/chrisspiegl.asc> fingerprint: 6646
6F22 1B88 A080 7748 E6F9 318B A27E 4ACD 1AC9
