### ISSUE TITLE
Not working: TypeError: UniversalSpeedtest is not a constructor

### ISSUE THREAD

**Issue by CharDSonDev** [karelkryda/universal-speedtest#8]
![image](https://user-images.githubusercontent.com/36754778/143625407-5b9f98f0-9475-48c5-9d74-5432234e61dc.png)

**Comment by karelkryda** [comment]
Good day,

I see you've found the documentation for Universal Speedtest v2 🙂.
The current release of Universal Speedtest is still v1. I am currently working on v2 and it should be released in the coming weeks. Documentation for v1 is available in the Wiki tab, but I would recommend waiting for the v2 release.

Thank you for understanding

**Comment by CharDSonDev** [comment]
Thanks for advising.

**Comment by karelkryda** [comment]
Hello,
I would like to inform you that a beta version of **Universal Speedtest v2** has been released, which contacts measuring servers without using Puppeteer (chromium browser) and should solve most problems.

For this reason, I am now closing this issue, but if you find a problem, do not hesitate to open a new problem.

Thank you for understanding
